name: Auto Image Rebuild
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: plaexmstr/caddy-custom:latest

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: plaexmstr/caddy-custom:alpine
          file: "Dockerfile.alpine"
